Lucene.Net.Store.AlreadyClosedException: For parity with Lucene, resurrected this exception type, but marked it internal, since we only want users to catch ObjectDisposedException